exports.sewabot = (botName) =>  {
      return `*「 SEWA GRUP BOT SKIMURA 」*

→ *ADA SISTEM BUAT MENJAGA GRUP ANDA*

╭☞ ANTILINK
╭☞ ANTIWAME
╭☞ ANTIBADWORD
╭☞ ANTILINKIG
╭☞ ANTILINKYT

→ *KEUNTUNGAN SEWA GRUP BOT SKIMURA*

╭☞ ANTILINK ADALAH YANG MENGGIRIM LINK GC LAIN DAN OTOMATIS DIKICK OLEH BOT
╭☞ ANTIWAME ADALAH YANG MENGGIRIM LINK WA.ME DAN OTOMATIS DIKICK
╭☞ ANTIBADWORD ADALAH YANG MENGGIRIM KATA KATA KASAR DAN OTOMATIS PERINGATAN 3X ATAU TIDAK ANDA DIKICK
╭☞ ANTILINKIG ADALAH YANG MENGGIRIM LINK TAUTAN IG DAN OTOMATIS DIKICK
╭☞ ANTILINKYT ADALAH YANG MENGGIRIM LINK YOUTUBE AKAN OTOMATIS DIKICK

→ *ORDER? SILAHKAN CHAT DIBAWAH INI*

↝ https://bit.ly/3mGfrhb

GITHUB : https://github.com/Rhmn9`
}
