exports.rules = (botName) => {
         return `「 RULES SKIMURA BOT 」
         
• JANGAN VC/TELPON BOT SKIMURA AUTO BLOCK
• BOT INI AUTO RESPON KALAU ANDA KIRIM CMD
• BOT SKIMURA TIDAK MENERIMA SEWA BOT GRATIS!
• JANGAN SPAM PADA BOT INI! KALAU SPAM NANTI ANDA TERBLOCK
• BOT INI MENGGUNAKAN PAKET/TERMUX/NGOPI DULU BANG
• TIDAK MENERIMA GRATIS USER PREMIUM!

                         「 SKIMURA BOT 」`
}